// <auto-generated />
using System;
using DDD.Data.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDD.Data.Questionario.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20180821202921_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MentalClean.Domain.Questionario.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Nome")
                        .HasMaxLength(125);

                    b.Property<string>("Tipo")
                        .HasMaxLength(125);

                    b.HasKey("Id");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("MentalClean.Domain.Questionario.Entities.Fruta", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Nome")
                        .HasMaxLength(125);

                    b.Property<string>("Tipo")
                        .HasMaxLength(125);

                    b.HasKey("Id");

                    b.ToTable("Fruta");
                });

            modelBuilder.Entity("MentalClean.Domain.Questionario.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Nome")
                        .HasMaxLength(125);

                    b.Property<string>("Profissao")
                        .HasMaxLength(125);

                    b.Property<string>("Sexo")
                        .HasMaxLength(125);

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(125);

                    b.HasKey("Id");

                    b.ToTable("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
